#!/usr/bin/env python
# coding: utf-8

#1
import numpy as np
my_arr = np.arange(50,101)
print(my_arr)


# 2
a = (1,1,1,1,1,1,1,1,1,1)
b = (0,0,0,0,0,0,0,0,0,0)
c = (6,6,6,6,6,6,6,6,6,6)

mass1 = np.array(a)
mass2 = np.array(b)
mass3 = np.array(c)

print(mass1)
print(mass2)
print(mass3)


# 3
data1 = np.arange(20,32)
a = np.reshape(data1, (3,4), 'C')
print(a)

data1 = np.arange(21,33)
b = np.reshape(data1, (3,4), 'C')
print(b)


# 4
c = ([0,0,1],[0,1,0],[1,0,0])
kk = np.array(c)
print(kk)


# 5
s = ([0,0,0,0,5],[0,0,0,4,0],[0,0,3,0,0],[0,2,0,0,0],[1,0,0,0,0])
ll = np.array(s)
print(ll)


